source 'https://rubygems.org'

gem 'rails'
gem 'bcrypt'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'sass-rails'
gem 'bootstrap-sass'
gem 'uglifier'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'sdoc', group: :doc

group :development, :test do
  gem 'mysql2'
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
end

group :test do
  gem 'minitest-reporters'
  gem 'mini_backtrace'
  gem 'guard'
  gem 'guard-minitest'
end